In [13]:
import numpy as np
import pandas as pd
import math

# PART B

### Task B1

In [19]:

df =pd.read_csv("/content/drive/MyDrive/alok_sir_project/Machine-Learning-Diabetic-Patient/diabetic_data.csv")
# first few records
df = df.sample(n=10000, random_state=42).reset_index(drop=True)
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,110939484,19274094,Caucasian,Female,[70-80),?,1,1,6,11,...,No,Steady,No,No,No,No,No,No,Yes,NO
1,170328306,65634327,Caucasian,Male,[50-60),?,1,1,1,1,...,No,No,No,No,No,No,No,No,Yes,NO
2,245688426,100657359,Caucasian,Female,[60-70),?,3,6,1,4,...,No,No,No,No,No,No,No,No,Yes,NO
3,150826224,83144448,Caucasian,Male,[30-40),?,2,1,1,12,...,No,No,No,No,No,No,No,No,Yes,>30
4,135993852,65234214,AfricanAmerican,Female,[60-70),?,1,2,7,1,...,No,No,No,No,No,No,No,No,Yes,<30

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
# last few records
df.tail()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
9995,139775880,54965709,AfricanAmerican,Female,[60-70),?,2,1,7,2,...,No,No,No,No,No,No,No,Ch,Yes,NO
9996,220128360,27949941,Caucasian,Male,[70-80),?,1,6,7,10,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
9997,224239608,102047796,Caucasian,Male,[70-80),?,2,1,7,3,...,No,No,No,No,No,No,No,No,No,<30
9998,210518988,85361247,Caucasian,Male,[80-90),?,1,3,7,10,...,No,No,No,No,No,No,No,No,No,>30
9999,165745332,90582291,Caucasian,Male,[80-90),?,1,1,7,1,...,No,No,No,No,No,No,No,No,No,NO

In [22]:
# shape
print("shape :",df.shape)
print("no of records :",df.shape[0])
print("no of features :",df.shape[1])

shape : (10000, 50)
no of records : 10000
no of features : 50

In [23]:
# gives the data type of features
# df.info()
count =0
for col in df.columns:
    print(count,"  ",col,"  ",type(df[col][0]).__name__,"\n")
    count+=1

0    encounter_id    int64

1    patient_nbr    int64

2    race    str

3    gender    str

4    age    str

5    weight    str

6    admission_type_id    int64

7    discharge_disposition_id    int64

8    admission_source_id    int64

9    time_in_hospital    int64

10    payer_code    str

11    medical_specialty    str

12    num_lab_procedures    int64

13    num_procedures    int64

14    num_medications    int64

15    number_outpatient    int64

16    number_emergency    int64

17    number_inpatient    int64

18    diag_1    str

19    diag_2    str

20    diag_3    str

21    number_diagnoses    int64

22    max_glu_serum    float

23    A1Cresult    float

24    metformin    str

25    repaglinide    str

26    nateglinide    str

27    chlorpropamide    str

28    glimepiride    str

29    acetohexamide    str

30    glipizide    str

31    glyburide    str

32    tolbutamide    str

33    pioglitazone    str

34    rosiglitazone    str

35    acarbose    str

36    miglitol    str

37    troglitazone    str

38    tolazamide    str

39    examide    str

40    citoglipton    str

41    insulin    str

42    glyburide-metformin    str

43    glipizide-metformin    str

44    glimepiride-pioglitazone    str

45    metformin-rosiglitazone    str

46    metformin-pioglitazone    str

47    change    str

48    diabetesMed    str

49    readmitted    str

In [24]:
# no of unique values
df.nunique()

uniques =[]
for col in df.columns:
    uniques.append(len(df[col].unique()))
data ={
    "column":df.columns,
    "unique_values":uniques
}
Nunique =pd.DataFrame(data)
Nunique

                      column  unique_values
0               encounter_id          10000
1                patient_nbr           9496
2                       race              6
3                     gender              3
4                        age             10
5                     weight             10
6          admission_type_id              7
7   discharge_disposition_id             21
8        admission_source_id             12
9           time_in_hospital             14
10                payer_code             17
11         medical_specialty             56
12        num_lab_procedures            104
13            num_procedures              7
14           num_medications             66
15         number_outpatient             24
16          number_emergency             16
17          number_inpatient             16
18                    diag_1            449
19                    diag_2            446
20                    diag_3            463
21          number_diagnoses             15
22             max_glu_serum              4
23                 A1Cresult              4
24                 metformin              4
25               repaglinide              4
26               nateglinide              4
27            chlorpropamide              3
28               glimepiride              4
29             acetohexamide              1
30                 glipizide              4
31                 glyburide              4
32               tolbutamide              2
33              pioglitazone              4
34             rosiglitazone              4
35                  acarbose              3
36                  miglitol              3
37              troglitazone              1
38                tolazamide              2
39                   examide              1
40               citoglipton              1
41                   insulin              4
42       glyburide-metformin              2
43       glipizide-metformin              1
44  glimepiride-pioglitazone              1
45   metformin-rosiglitazone              1
46    metformin-pioglitazone              1
47                    change              2
48               diabetesMed              2
49                readmitted              3

In [25]:
# columns with null values
df.isnull().sum()

encounter_id                   0
patient_nbr                    0
race                           0
gender                         0
age                            0
weight                         0
admission_type_id              0
discharge_disposition_id       0
admission_source_id            0
time_in_hospital               0
payer_code                     0
medical_specialty              0
num_lab_procedures             0
num_procedures                 0
num_medications                0
number_outpatient              0
number_emergency               0
number_inpatient               0
diag_1                         0
diag_2                         0
diag_3                         0
number_diagnoses               0
max_glu_serum               9475
A1Cresult                   8335
metformin                      0
repaglinide                    0
nateglinide                    0
chlorpropamide                 0
glimepiride                    0
acetohexamide                  0
glipizide                      0
glyburide                      0
tolbutamide                    0
pioglitazone                   0
rosiglitazone                  0
acarbose                       0
miglitol                       0
troglitazone                   0
tolazamide                     0
examide                        0
citoglipton                    0
insulin                        0
glyburide-metformin            0
glipizide-metformin            0
glimepiride-pioglitazone       0
metformin-rosiglitazone        0
metformin-pioglitazone         0
change                         0
diabetesMed                    0
readmitted                     0
dtype: int64

# PART J Train_test_split

In [26]:
# Calulating the no of rows in the trainign and testing
train_rows =round(80*df.shape[0]/100)
test_rows =df.shape[0]-train_rows
print("training Rows ",train_rows,"testing rows ",test_rows)
 # train-test_split
train =df.sample(train_rows,random_state=42)
test = df.drop(train.index)
# spliting the features and target of training data
y_train =train["readmitted"]
x_train =train.drop(columns="readmitted",axis =1)
# spliting the features and target of texting data
y_test =test["readmitted"]
x_test =test.drop(columns="readmitted",axis =1)
print("x_train " ,x_train.shape)
print("y_train " ,y_train.shape)
print("x_test " ,x_test.shape)
print("y_test " ,y_test.shape)

training Rows  8000 testing rows  2000
x_train  (8000, 49)
y_train  (8000,)
x_test  (2000, 49)
y_test  (2000,)

In [27]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.000000e+04,1.000000e+04,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,1.636509e+08,5.440939e+07,2.03840,3.721500,5.779800,4.368800,43.342600,1.335200,16.085800,0.383400,0.197300,0.637400,7.40350
std,1.018809e+08,3.869557e+07,1.46258,5.230437,4.082742,2.941879,19.360302,1.708254,8.152882,1.358156,1.068029,1.254463,1.93532
min,1.839300e+05,2.025000e+03,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.00000
25%,8.435905e+07,2.340213e+07,1.00000,1.000000,1.000000,2.000000,32.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.00000
50%,1.515235e+08,4.566950e+07,1.00000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.00000
75%,2.280187e+08,8.826741e+07,3.00000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.00000
max,4.438472e+08,1.895026e+08,8.00000,28.000000,22.000000,14.000000,126.000000,6.000000,69.000000,42.000000,63.000000,21.000000,16.00000

### Task b2

In [28]:
numerical_features =df.select_dtypes(include ="number").columns
numerical_features,len(numerical_features)

(Index(['encounter_id', 'patient_nbr', 'admission_type_id',
        'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
        'num_lab_procedures', 'num_procedures', 'num_medications',
        'number_outpatient', 'number_emergency', 'number_inpatient',
        'number_diagnoses'],
       dtype='object'),
 13)

In [32]:
# mean
print("calculation",numerical_features)
x_train_mean =[]
for col in numerical_features:
    sum_ =0
    count_ =0
    for m in x_train[col]:
        count_+=1
        sum_=sum_+m
    mean_ =sum_/count_
    x_train_mean.append(mean_)
print("mean",x_train_mean)

# minimum and maximum
x_train_min =[]
x_train_max =[]
for col in numerical_features:
    max_ =0
    min_= 1000000009
    for m in x_train[col]:
        if m>max_:max_ =m
        if m<min_:min_ =m
    x_train_min.append(min_)
    x_train_max.append(max_)
print("minimum" ,x_train_min)
print("maximum", x_train_max)

# mode
x_train_mode =[]
for col in numerical_features:
    mode_ =x_train[col].mode()[0]
    x_train_mode.append(mode_)
print("mode",x_train_mode)

x_train_median = []

for col in numerical_features:
    x_sort = x_train[col].sort_values().reset_index(drop=True)
    n = len(x_sort)

    if n % 2 == 0:
        median_ = (x_sort.iloc[n // 2 - 1] + x_sort.iloc[n // 2]) / 2
    else:
        median_ = x_sort.iloc[n // 2]

    x_train_median.append(median_)

print("median", x_train_median)

# Standard_deviation and variance
x_train_std =[]
x_train_var =[]
cc =0
for col in numerical_features:
    val =0
    for i in x_train[col]:
        val+=(i-x_train_mean[cc])**2
    var =val/(x_train.shape[0]-1)
    val =math.sqrt(val/x_train.shape[0])
    x_train_std.append(val)
    cc+=1
    x_train_var.append(var)
print("standard_deviation",x_train_std)
print("variance",x_train_var)

# making a dataframe
stat_df =pd.DataFrame({
    "features":numerical_features,
    "mean":x_train_mean,
    "median":x_train_median,
    "mode":x_train_mode,
    "standard_deviation":x_train_std,
    "variance":x_train_var,
    "minimum":x_train_min,
    "maximum":x_train_max
})

calculation Index(['encounter_id', 'patient_nbr', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses'],
      dtype='object')
mean [163658327.855, 54613098.791, 2.03175, 3.704125, 5.786875, 4.3845, 43.453125, 1.335125, 16.047625, 0.39125, 0.202125, 0.642125, 7.417125]
minimum [183930, 2025, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1]
maximum [443847176, 189502619, 8, 28, 22, 14, 113, 6, 69, 42, 63, 16, 16]
mode [np.int64(183930), np.int64(6142500), np.int64(1), np.int64(1), np.int64(7), np.int64(3), np.int64(43), np.int64(0), np.int64(13), np.int64(0), np.int64(0), np.int64(0), np.int64(9)]
median [np.float64(151719339.0), np.float64(46053058.5), np.float64(1.0), np.float64(1.0), np.float64(7.0), np.float64(4.0), np.float64(44.0), np.float64(1.0), np.float64(15.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(8.0)]
standard_deviation [101622034.55769734, 38805075.51499158, 1.4617598768265188, 5.186167465901497, 4.069791485368244, 2.9457867794529773, 19.330036283834932, 1.717357340326971, 8.14282548378478, 1.404251913831653, 1.1434686197594728, 1.2581933414125401, 1.9298009571908206]
variance [1.0328328948764428e+16, 1506022138491510.5, 2.1370090636328336, 26.899695446305948, 16.565273393550047, 8.678744593074077, 373.6970148612327, 2.9496849449930522, 66.31389609638688, 1.972169958744703, 1.3076839448677424, 1.5832483904236554, 3.7245973090382374]

In [33]:
stat_df

,features,mean,median,mode,standard_deviation,variance,minimum,maximum
0,encounter_id,1.636583e+08,151719339.0,183930,1.016220e+08,1.032833e+16,183930,443847176
1,patient_nbr,5.461310e+07,46053058.5,6142500,3.880508e+07,1.506022e+15,2025,189502619
2,admission_type_id,2.031750e+00,1.0,1,1.461760e+00,2.137009e+00,1,8
3,discharge_disposition_id,3.704125e+00,1.0,1,5.186167e+00,2.689970e+01,1,28
4,admission_source_id,5.786875e+00,7.0,7,4.069791e+00,1.656527e+01,1,22
5,time_in_hospital,4.384500e+00,4.0,3,2.945787e+00,8.678745e+00,1,14
6,num_lab_procedures,4.345312e+01,44.0,43,1.933004e+01,3.736970e+02,1,113
7,num_procedures,1.335125e+00,1.0,0,1.717357e+00,2.949685e+00,0,6
8,num_medications,1.604763e+01,15.0,13,8.142825e+00,6.631390e+01,1,69
9,number_outpatient,3.912500e-01,0.0,0,1.404252e+00,1.972170e+00,0,42
10,number_emergency,2.021250e-01,0.0,0,1.143469e+00,1.307684e+00,0,63
11,number_inpatient,6.421250e-01,0.0,0,1.258193e+00,1.583248e+00,0,16
12,number_diagnoses,7.417125e+00,8.0,9,1.929801e+00,3.724597e+00,1,16

In [34]:
x_train.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,8.000000e+03,8.000000e+03,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000,8000.000000,8000.000000,8000.000000
mean,1.636583e+08,5.461310e+07,2.031750,3.704125,5.786875,4.384500,43.453125,1.335125,16.047625,0.39125,0.202125,0.642125,7.417125
std,1.016284e+08,3.880750e+07,1.461851,5.186492,4.070046,2.945971,19.331245,1.717465,8.143334,1.40434,1.143540,1.258272,1.929922
min,1.839300e+05,2.025000e+03,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.00000,0.000000,0.000000,1.000000
25%,8.435259e+07,2.342051e+07,1.000000,1.000000,1.000000,2.000000,32.000000,0.000000,10.000000,0.00000,0.000000,0.000000,6.000000
50%,1.517193e+08,4.605306e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.00000,0.000000,0.000000,8.000000
75%,2.270658e+08,8.853117e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.00000,0.000000,1.000000,9.000000
max,4.438472e+08,1.895026e+08,8.000000,28.000000,22.000000,14.000000,113.000000,6.000000,69.000000,42.00000,63.000000,16.000000,16.000000

# PART D  (Duplicate and invalid data)

### Task D1

In [35]:
# reseting the random index to sequential
x_train =x_train.reset_index(drop =True)

In [36]:
# finding duplicate records
x_train_dup = x_train.iloc[:, 2:]
x_duplicated = []
seen = set()
for i in range(len(x_train_dup)):
    row = tuple(x_train_dup.iloc[i])
    if row in seen:
        x_duplicated.append(i)
    else:
        seen.add(row)
print("no of duplicate rows :",len(x_duplicated))
    # no duplicate records find

no of duplicate rows : 0

### Task D2

In [37]:
# there is ? in multiple rows representing the null value
print("columns","count","percentage")
null_cols =[]
for col in x_train.columns:
    c =x_train[x_train[col]=="?"]
    if len(c)>0 :
        null_cols.append(col)
        p =len(c)*100/x_train.shape[0]
        print(col,"  ",len(c),"  ",p)

columns count percentage
race    187    2.3375
weight    7729    96.6125
payer_code    3195    39.9375
medical_specialty    3901    48.7625
diag_1    2    0.025
diag_2    25    0.3125
diag_3    105    1.3125

In [38]:
# replaceing all '?' with the nan valule

# for col in null_cols:
#     for i in x_train.index:
#         if x_train[col][i]=="?":
#             x_train.loc[i,col] =np.nan
x_train =x_train.replace("?",np.nan)
x_train

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed
0,214993092,86186484,Caucasian,Female,[80-90),NaN,1,1,1,2,...,No,No,No,No,No,No,No,No,No,Yes
1,234970404,50871051,Caucasian,Female,[50-60),NaN,1,1,7,3,...,No,No,No,No,No,No,No,No,Ch,Yes
2,48715776,23410206,AfricanAmerican,Female,[70-80),NaN,1,3,17,5,...,No,No,Down,No,No,No,No,No,Ch,Yes
3,225775440,113902974,Caucasian,Male,[40-50),[175-200),1,6,7,6,...,No,No,No,No,No,No,No,No,Ch,Yes
4,239625456,51795837,Caucasian,Male,[40-50),NaN,1,1,7,2,...,No,No,Up,No,No,No,No,No,Ch,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,62494218,2594745,Caucasian,Female,[30-40),NaN,1,1,7,4,...,No,No,No,No,No,No,No,No,Ch,Yes
7996,26008086,86588775,Caucasian,Female,[60-70),NaN,1,1,7,2,...,No,No,Steady,No,No,No,No,No,Ch,Yes
7997,137878476,86624991,Caucasian,Male,[50-60),NaN,1,7,7,2,...,No,No,No,No,No,No,No,No,No,No
7998,14067864,411642,Caucasian,Female,[60-70),NaN,1,1,7,9,...,No,No,Down,No,No,No,No,No,Ch,Yes
7999,38839590,140175,AfricanAmerican,Female,[40-50),NaN,1,18,7,6,...,No,No,No,No,No,No,No,No,No,No

In [39]:
# replacing the values of hte columns with "ch" to Yes
print("columns")
ch_val =[]
for col in x_train.columns:
    c =x_train[x_train[col]=="Ch"]
    if len(c)>0 :
        ch_val.append(col)
# for col in ch_val:
#     for i in range(len(x_train)):
#         if x_train[col][i] =="Ch":
#             x_train.loc[i,col]="Yes"
x_train =x_train.replace("Ch","YES")
x_train["change"]

columns

0        No
1       YES
2       YES
3       YES
4       YES
       ...
7995    YES
7996    YES
7997     No
7998    YES
7999     No
Name: change, Length: 8000, dtype: object

# PART C MISSING VALUES

### TASK C1

In [40]:
# Null values before imputation
null_cols =[]
print("features  ","count  ","percentage")
for col in x_train.columns:
    c =x_train[x_train[col].isna()]
    if len(c)>0:
        null_cols.append(col)
        p =len(c)*100/x_train.shape[0]
        print(col,"  ",len(c),"  ",p)

features   count   percentage
race    187    2.3375
weight    7729    96.6125
payer_code    3195    39.9375
medical_specialty    3901    48.7625
diag_1    2    0.025
diag_2    25    0.3125
diag_3    105    1.3125
max_glu_serum    7592    94.9
A1Cresult    6653    83.1625

In [41]:
# columns to be removed directly:
# 1). weight :since it has 96% NaN data
# 2). payer_code : As it is kind of id which is different for all the person so not that much imp
# 3). Max_glu_serum : it has 94% NaN data
# 4).A1Cresult : it has 83% NaN data
x_train = x_train.drop(columns =["weight","payer_code","max_glu_serum","A1Cresult","medical_specialty"],axis =1)
x_train
x_test = x_test.drop(columns =["weight","payer_code","max_glu_serum","A1Cresult","medical_specialty"],axis =1)

# columns which are representing the patient unique number so it can be removed
# 1).encounter_id as it is patient no is unique
# 2).patient_nbr it is also a patient id is fixed for every patient
x_train = x_train.drop(columns=["encounter_id","patient_nbr"],axis=1)
x_test = x_test.drop(columns=["encounter_id","patient_nbr"],axis=1)
x_test.shape,x_train.shape

((2000, 42), (8000, 42))

In [43]:
unidiag =[];
diag =x_train["diag_1"].unique()
def categorise_icd9(code):
  # code =code.strip()
  if type(code) !=str and pd.isna(code):return "Missing"
  elif type(code)==str and code[0]=='V':return "Supplementary Factor"
  elif type(code) ==str and code[0]=='E':return "External Factor"
  num =float(code)
  if 250<=num<251:return "Diabetes"
  base =int(num)
  ranges = [
        (1, 139, "Infectious & parasitic diseases"),
        (140, 239, "Neoplasms"),
        (240, 249, "Endocrine/metabolic (non-diabetic)"),
        (251, 279, "Endocrine/metabolic (non-diabetic)"),
        (280, 289, "Blood & blood-forming organs"),
        (290, 319, "Mental disorders"),
        (320, 359, "Nervous system & sense organs"),
        (360, 389, "Sense organs (eye/ear)"),
        (390, 459, "Circulatory diseases"),
        (460, 519, "Respiratory diseases"),
        (520, 579, "Digestive diseases"),
        (580, 629, "Genitourinary diseases"),
        (630, 679, "Pregnancy/childbirth complications"),
        (680, 709, "Skin & subcutaneous tissue"),
        (710, 739, "Musculoskeletal & connective tissue"),
        (740, 759, "Congenital anomalies"),
        (760, 779, "Perinatal conditions"),
        (780, 799, "Symptoms/signs/ill-defined conditions"),
        (800, 999, "Injury & poisoning"),
    ]
  for low,high,label in ranges:
      if low<=base<=high:return label

In [44]:
for diag in ["diag_1","diag_2","diag_3"]:
  for i in range(x_train.shape[0]):
    x_train[diag][i]=categorise_icd9(x_train[diag][i])
x_train[ ["diag_1","diag_2","diag_3"]]

Streaming output truncated to the last 5000 lines.
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train[diag][i]=categorise_icd9(x_train[diag][i])
/tmp/ipykernel_1793/3483353976.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train[diag][i]=categorise_icd9(x_train[diag][i])

,diag_1,diag_2,diag_3
0,Circulatory diseases,Genitourinary diseases,Circulatory diseases
1,Respiratory diseases,Respiratory diseases,Musculoskeletal & connective tissue
2,Circulatory diseases,Endocrine/metabolic (non-diabetic),Circulatory diseases
3,Skin & subcutaneous tissue,Diabetes,Circulatory diseases
4,Infectious & parasitic diseases,Injury & poisoning,Genitourinary diseases
...,...,...,...
7995,Mental disorders,Diabetes,Circulatory diseases
7996,Circulatory diseases,Circulatory diseases,Musculoskeletal & connective tissue
7997,Skin & subcutaneous tissue,Mental disorders,Diabetes
7998,Injury & poisoning,Respiratory diseases,Endocrine/metabolic (non-diabetic)
7999,Respiratory diseases,Symptoms/signs/ill-defined conditions,Mental disorders

In [45]:
# race
count = {}

for i in range(len(x_train["race"])):
    value = x_train["race"].iloc[i]

    if value == value:  # checks if value is NOT NaN
        if value in count:
            count[value] = count[value] + 1
        else:
            count[value] = 1

print(count)

{'Caucasian': 5940, 'AfricanAmerican': 1549, 'Hispanic': 165, 'Asian': 37, 'Other': 122}

In [46]:
max_count = 0
mode_race = None

for key in count:
    if count[key] > max_count:
        max_count = count[key]
        mode_race = key

print("Mode:", mode_race)

Mode: Caucasian

In [47]:
for i in range(len(x_train["race"])):
    if x_train["race"].iloc[i] != x_train["race"].iloc[i]:
        x_train.loc[x_train.index[i], "race"] = mode_race

In [48]:
x_train["race"]
x_train["race"].unique()

array(['Caucasian', 'AfricanAmerican', 'Hispanic', 'Asian', 'Other'],
      dtype=object)