In [1]:
import numpy as np
import pandas as pd
import math

# PART B

### Task B1

In [4]:

df =pd.read_csv("diabetic_data.csv")
# first few records
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [5]:
# last few records
df.tail()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [6]:
# shape
df.shape
print("no of records :",df.shape[0])
print("no of features :",df.shape[1])

no of records : 101766
no of features : 50

In [7]:
# gives the data type of features 
# df.info()
count =0
for col in df.columns:
    print(count,"  ",col,"  ",type(df[col][0]).__name__,"\n")
    count+=1

0    encounter_id    int64

1    patient_nbr    int64

2    race    str

3    gender    str

4    age    str

5    weight    str

6    admission_type_id    int64

7    discharge_disposition_id    int64

8    admission_source_id    int64

9    time_in_hospital    int64

10    payer_code    str

11    medical_specialty    str

12    num_lab_procedures    int64

13    num_procedures    int64

14    num_medications    int64

15    number_outpatient    int64

16    number_emergency    int64

17    number_inpatient    int64

18    diag_1    str

19    diag_2    str

20    diag_3    str

21    number_diagnoses    int64

22    max_glu_serum    float

23    A1Cresult    float

24    metformin    str

25    repaglinide    str

26    nateglinide    str

27    chlorpropamide    str

28    glimepiride    str

29    acetohexamide    str

30    glipizide    str

31    glyburide    str

32    tolbutamide    str

33    pioglitazone    str

34    rosiglitazone    str

35    acarbose    str

36    miglitol    str

37    troglitazone    str

38    tolazamide    str

39    examide    str

40    citoglipton    str

41    insulin    str

42    glyburide-metformin    str

43    glipizide-metformin    str

44    glimepiride-pioglitazone    str

45    metformin-rosiglitazone    str

46    metformin-pioglitazone    str

47    change    str

48    diabetesMed    str

49    readmitted    str

In [8]:
# no of unique values
df.nunique()

uniques =[]
for col in df.columns:
    uniques.append(len(df[col].unique()))
data ={
    "column":df.columns,
    "unique_values":uniques
}
Nunique =pd.DataFrame(data)
Nunique

                      column  unique_values
0               encounter_id         101766
1                patient_nbr          71518
2                       race              6
3                     gender              3
4                        age             10
5                     weight             10
6          admission_type_id              8
7   discharge_disposition_id             26
8        admission_source_id             17
9           time_in_hospital             14
10                payer_code             18
11         medical_specialty             73
12        num_lab_procedures            118
13            num_procedures              7
14           num_medications             75
15         number_outpatient             39
16          number_emergency             33
17          number_inpatient             21
18                    diag_1            717
19                    diag_2            749
20                    diag_3            790
21          number_diagnoses             16
22             max_glu_serum              4
23                 A1Cresult              4
24                 metformin              4
25               repaglinide              4
26               nateglinide              4
27            chlorpropamide              4
28               glimepiride              4
29             acetohexamide              2
30                 glipizide              4
31                 glyburide              4
32               tolbutamide              2
33              pioglitazone              4
34             rosiglitazone              4
35                  acarbose              4
36                  miglitol              4
37              troglitazone              2
38                tolazamide              3
39                   examide              1
40               citoglipton              1
41                   insulin              4
42       glyburide-metformin              4
43       glipizide-metformin              2
44  glimepiride-pioglitazone              2
45   metformin-rosiglitazone              2
46    metformin-pioglitazone              2
47                    change              2
48               diabetesMed              2
49                readmitted              3

In [9]:
# columns with null values
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

# PART J Train_test_split

In [11]:
# Calulating the no of rows in the trainign and testing
train_rows =round(80*df.shape[0]/100)
test_rows =df.shape[0]-train_rows
print("training Rows ",train_rows,"testing rows ",test_rows)
 # train-test_split
train =df.sample(train_rows,random_state=42)
test = df.drop(train.index)
# spliting the features and target of training data
y_train =train["readmitted"]
x_train =train.drop(columns="readmitted",axis =1)
# spliting the features and target of texting data
y_test =test["readmitted"]
x_test =test.drop(columns="readmitted",axis =1)
print("x_train " ,x_train.shape)
print("y_train " ,y_train.shape)
print("x_test " ,x_test.shape)
print("y_test " ,y_test.shape)

training Rows  81413 testing rows  20353
x_train  (81413, 49)
y_train  (81413,)
x_test  (20353, 49)
y_test  (20353,)

In [12]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

### Task b2

In [14]:
numerical_features =df.select_dtypes(include ="number").columns
numerical_features,len(numerical_features)

(Index(['encounter_id', 'patient_nbr', 'admission_type_id',
        'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
        'num_lab_procedures', 'num_procedures', 'num_medications',
        'number_outpatient', 'number_emergency', 'number_inpatient',
        'number_diagnoses'],
       dtype='object'),
 13)

In [15]:
# mean
print("calculation",numerical_features)
x_train_mean =[]
for col in numerical_features:
    sum_ =0
    count_ =0
    for m in x_train[col]:
        count_+=1
        sum_=sum_+m 
    mean_ =sum_/count_
    x_train_mean.append(mean_)
print("mean",x_train_mean)

# minimum and maximum
x_train_min =[]
x_train_max =[]
for col in numerical_features:
    max_ =0
    min_= 1000000009
    for m in x_train[col]:
        if m>max_:max_ =m
        if m<min_:min_ =m
    x_train_min.append(min_)
    x_train_max.append(max_)
print("minimum" ,x_train_min)
print("maximum", x_train_max)

# mode
x_train_mode =[]
for col in numerical_features:
    mode_ =x_train[col].mode()[0]
    x_train_mode.append(mode_)
print("mode",x_train_mode)

# median
x_train_median=[]
for col in numerical_features:
    x_sort =x_train[col].sort_values()
    if len(x_sort)%2==0:
        median_ =x_sort[len(x_sort)/2]
        x_train_median.append(median_)
    else:
        median_ =x_sort[len(x_sort)+1//2]
        x_train_median.append(median_)
print("median",x_train_median)

# Standard_deviation and variance
x_train_std =[]
x_train_var =[]
cc =0
for col in numerical_features:
    val =0
    for i in x_train[col]:
        val+=(i-x_train_mean[cc])**2
    var =val/(x_train.shape[0]-1)
    val =math.sqrt(val/x_train.shape[0])
    x_train_std.append(val)
    cc+=1
    x_train_var.append(var)
print("standard_deviation",x_train_std)
print("variance",x_train_var)

# making a dataframe
stat_df =pd.DataFrame({
    "features":numerical_features,
    "mean":x_train_mean,
    "median":x_train_median,
    "mode":x_train_mode,
    "standard_deviation":x_train_std,
    "variance":x_train_var,
    "minimum":x_train_min,
    "maximum":x_train_max
})

calculation Index(['encounter_id', 'patient_nbr', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses'],
      dtype='object')
mean [165380681.66297767, 54450618.71967622, 2.0225393978848585, 3.7047645953348973, 5.753909080859322, 4.387898738530701, 43.071413656295675, 1.33841032758896, 16.01626275901883, 0.3718325083217668, 0.19668848955326546, 0.6360286440740422, 7.425177797157702]
minimum [12522, 135, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1]
maximum [443867222, 189502619, 8, 28, 25, 14, 132, 6, 81, 42, 76, 21, 16]
mode [12522, 88785891, 1, 1, 7, 3, 1, 0, 13, 0, 0, 0, 9]
median [252314172, 32776020, 2, 6, 1, 6, 64, 0, 14, 0, 0, 0, 9]
standard_deviation [102533965.65436561, 38711907.747742325, 1.4446568026007252, 5.261099058265525, 4.057992528314589, 2.9819863741549457, 19.66325987947485, 1.7047472268400048, 8.09999055122586, 1.2612209262092466, 0.9222766503612625, 1.2602413582330396, 1.9311585448970803]
variance [1.0513343248737918e+16, 1498630209220430.8, 2.0870589127508197, 27.679503289622385, 16.467505631062256, 8.892351960855011, 386.64853831133286, 2.906198804405709, 65.61065282891803, 1.5906977633292556, 0.8506046678217816, 1.5882277892833858, 3.729419134173011]

In [16]:
stat_df

,features,mean,median,mode,standard_deviation,variance,minimum,maximum
0,encounter_id,1.653807e+08,252314172,12522,1.025340e+08,1.051334e+16,12522,443867222
1,patient_nbr,5.445062e+07,32776020,88785891,3.871191e+07,1.498630e+15,135,189502619
2,admission_type_id,2.022539e+00,2,1,1.444657e+00,2.087059e+00,1,8
3,discharge_disposition_id,3.704765e+00,6,1,5.261099e+00,2.767950e+01,1,28
4,admission_source_id,5.753909e+00,1,7,4.057993e+00,1.646751e+01,1,25
5,time_in_hospital,4.387899e+00,6,3,2.981986e+00,8.892352e+00,1,14
6,num_lab_procedures,4.307141e+01,64,1,1.966326e+01,3.866485e+02,1,132
7,num_procedures,1.338410e+00,0,0,1.704747e+00,2.906199e+00,0,6
8,num_medications,1.601626e+01,14,13,8.099991e+00,6.561065e+01,1,81
9,number_outpatient,3.718325e-01,0,0,1.261221e+00,1.590698e+00,0,42
10,number_emergency,1.966885e-01,0,0,9.222767e-01,8.506047e-01,0,76
11,number_inpatient,6.360286e-01,0,0,1.260241e+00,1.588228e+00,0,21
12,number_diagnoses,7.425178e+00,9,9,1.931159e+00,3.729419e+00,1,16

In [17]:
x_train.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,8.141300e+04,8.141300e+04,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000,81413.000000
mean,1.653807e+08,5.445062e+07,2.022539,3.704765,5.753909,4.387899,43.071414,1.338410,16.016263,0.371833,0.196688,0.636029,7.425178
std,1.025346e+08,3.871215e+07,1.444666,5.261131,4.058017,2.982005,19.663381,1.704758,8.100040,1.261229,0.922282,1.260249,1.931170
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.543119e+07,2.342982e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.525887e+08,4.566946e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302019e+08,8.769585e+07,3.000000,3.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

# PART D  (Duplicate and invalid data)

### Task D1

In [20]:
# reseting the random index to sequential
x_train =x_train.reset_index(drop =True)

In [21]:
# finding duplicate records
x_train_dup = x_train.iloc[:, 2:]
x_duplicated = []
seen = set()
for i in range(len(x_train_dup)):
    row = tuple(x_train_dup.iloc[i])
    if row in seen:
        x_duplicated.append(i)
    else:
        seen.add(row)
print("no of duplicate rows :",len(x_duplicated))
    # no duplicate records find

no of duplicate rows : 0

### Task D2

In [23]:
# there is ? in multiple rows representing the null value
print("columns","count","percentage")
null_cols =[]
for col in x_train.columns:
    c =x_train[x_train[col]=="?"]
    if len(c)>0 :
        null_cols.append(col)
        p =len(c)*100/x_train.shape[0]
        print(col,"  ",len(c),"  ",p)

columns count percentage
race    1838    2.2576247036714037
weight    78829    96.8260597201921
payer_code    32098    39.42613587510594
medical_specialty    40029    49.1678233205999
diag_1    16    0.01965288098952256
diag_2    290    0.35620846793509636
diag_3    1117    1.3720167540810435

In [24]:
# replaceing all '?' with the nan valule

# for col in null_cols:
#     for i in x_train.index:
#         if x_train[col][i]=="?":
#             x_train.loc[i,col] =np.nan
x_train =x_train.replace("?",np.nan)
x_train

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed
0,110939484,19274094,Caucasian,Female,[70-80),NaN,1,1,6,11,...,No,No,Steady,No,No,No,No,No,No,Yes
1,170328306,65634327,Caucasian,Male,[50-60),NaN,1,1,1,1,...,No,No,No,No,No,No,No,No,No,Yes
2,245688426,100657359,Caucasian,Female,[60-70),NaN,3,6,1,4,...,No,No,No,No,No,No,No,No,No,Yes
3,150826224,83144448,Caucasian,Male,[30-40),NaN,2,1,1,12,...,No,No,No,No,No,No,No,No,No,Yes
4,135993852,65234214,AfricanAmerican,Female,[60-70),NaN,1,2,7,1,...,No,No,No,No,No,No,No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81408,48382938,18651474,AfricanAmerican,Male,[0-10),NaN,1,1,7,2,...,No,No,Steady,No,No,No,No,No,No,Yes
81409,2594658,5281155,Caucasian,Female,[70-80),NaN,6,25,7,5,...,No,No,No,No,No,No,No,No,No,No
81410,147943500,86765814,AfricanAmerican,Male,[70-80),NaN,1,1,7,11,...,No,No,No,No,No,No,No,No,No,Yes
81411,177480366,86043492,Caucasian,Female,[50-60),NaN,1,3,7,9,...,No,No,Steady,No,No,No,No,No,Ch,Yes
81412,55270032,69613551,Caucasian,Female,[20-30),NaN,2,1,7,5,...,No,No,Steady,No,No,No,No,No,No,Yes

In [25]:
# replacing the values of hte columns with "ch" to Yes 
print("columns")
ch_val =[]
for col in x_train.columns:
    c =x_train[x_train[col]=="Ch"]
    if len(c)>0 :
        ch_val.append(col)
# for col in ch_val:
#     for i in range(len(x_train)):
#         if x_train[col][i] =="Ch":
#             x_train.loc[i,col]="Yes" 
x_train =x_train.replace("Ch","YES")
x_train["change"]

columns

0         No
1         No
2         No
3         No
4         No
        ...
81408     No
81409     No
81410     No
81411    YES
81412     No
Name: change, Length: 81413, dtype: object

# PART C MISSING VALUES

### TASK C1

In [ ]:
null_cols =[]
for col in x_train.columns:
    c =x_train[x_train[col]=="?"]
    if len(c)>0 :
        null_cols.append(col)
        p =len(c)*100/x_train.shape[0]
        print(col,"  ",len(c),"  ",p)

In [26]:
# as from above code this columns are either id or with more than 40% null values so they are removed 
cols =["weight","payer_code","medical_specialty","encounter_id","patient_nbr"]
df.drop(cols,axis =1,inplace =True)
df.shape
# after this shape become (101766,45) from (101766,50)

(101766, 45)

In [27]:
# to get those featues which has a very huge  difference in then value_counts 
# so  that to remove those values to reduce sparsity.
uniques =[]
for col in df.columns:
    val =len(df[col].unique())
    if val<5:uniques.append([col,val])
Nunique =pd.DataFrame(uniques,columns =["columns","unique_value"])     

for i in range(len(Nunique)):
    ans =df[Nunique["columns"][i]].value_counts().to_dict()
    print(Nunique["columns"][i]," ",Nunique["unique_value"][i]," ",ans)

gender   3   {'Female': 54708, 'Male': 47055, 'Unknown/Invalid': 3}
max_glu_serum   4   {'Norm': 2597, '>200': 1485, '>300': 1264}
A1Cresult   4   {'>8': 8216, 'Norm': 4990, '>7': 3812}
metformin   4   {'No': 81778, 'Steady': 18346, 'Up': 1067, 'Down': 575}
repaglinide   4   {'No': 100227, 'Steady': 1384, 'Up': 110, 'Down': 45}
nateglinide   4   {'No': 101063, 'Steady': 668, 'Up': 24, 'Down': 11}
chlorpropamide   4   {'No': 101680, 'Steady': 79, 'Up': 6, 'Down': 1}
glimepiride   4   {'No': 96575, 'Steady': 4670, 'Up': 327, 'Down': 194}
acetohexamide   2   {'No': 101765, 'Steady': 1}
glipizide   4   {'No': 89080, 'Steady': 11356, 'Up': 770, 'Down': 560}
glyburide   4   {'No': 91116, 'Steady': 9274, 'Up': 812, 'Down': 564}
tolbutamide   2   {'No': 101743, 'Steady': 23}
pioglitazone   4   {'No': 94438, 'Steady': 6976, 'Up': 234, 'Down': 118}
rosiglitazone   4   {'No': 95401, 'Steady': 6100, 'Up': 178, 'Down': 87}
acarbose   4   {'No': 101458, 'Steady': 295, 'Up': 10, 'Down': 3}
miglitol   4   {'No': 101728, 'Steady': 31, 'Down': 5, 'Up': 2}
troglitazone   2   {'No': 101763, 'Steady': 3}
tolazamide   3   {'No': 101727, 'Steady': 38, 'Up': 1}
examide   1   {'No': 101766}
citoglipton   1   {'No': 101766}
insulin   4   {'No': 47383, 'Steady': 30849, 'Down': 12218, 'Up': 11316}
glyburide-metformin   4   {'No': 101060, 'Steady': 692, 'Up': 8, 'Down': 6}
glipizide-metformin   2   {'No': 101753, 'Steady': 13}
glimepiride-pioglitazone   2   {'No': 101765, 'Steady': 1}
metformin-rosiglitazone   2   {'No': 101764, 'Steady': 2}
metformin-pioglitazone   2   {'No': 101765, 'Steady': 1}
change   2   {'No': 54755, 'Ch': 47011}
diabetesMed   2   {'Yes': 78363, 'No': 23403}
readmitted   3   {'NO': 54864, '>30': 35545, '<30': 11357}

In [28]:
# droping those columns with only 1 unique values or with those columns which arae highly sparse dataa like only less than 0.1% data
ndf =[Nunique["columns"][i] for i in range(len(Nunique)) if Nunique["unique_value"][i]<=2]
ndf.remove("change")
ndf.remove("diabetesMed")
df.drop(ndf,axis =1,inplace =True)

In [29]:
ndf

['acetohexamide',
 'tolbutamide',
 'troglitazone',
 'examide',
 'citoglipton',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone']

In [30]:
# df[ndf].value_counts(normalize=True)